name: VoiceLog
options:
  useBaseInternationalization: false
  enableBaseInternationalization: false
  groupOrdering:
    - order: [Sources, Resources, Shared]
settings:
  MARKETING_VERSION: 0.3.2
  CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: true
  CODE_SIGN_STYLE: Automatic
  CURRENT_PROJECT_VERSION: 1
  VERSIONING_SYSTEM: apple-generic
packages:
  XLog:
    path: ./Packages/XLog
  XLang:
    path: ./Packages/XLang
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess.git
    from: 4.2.0
  ConfettiSwiftUI:
    url: https://github.com/simibac/ConfettiSwiftUI.git
    from: 1.1.0
  DSWaveformImage:
    url: https://github.com/dmrschmidt/DSWaveformImage
    from: 13.0.2
  CSV:
    url: https://github.com/yaslab/CSV.swift.git
    from: 2.4.3
  ArkanaKeys:
    path: ./ArkanaKeys/ArkanaKeys
  ArkanaKeysInterfaces:
    path: ./ArkanaKeys/ArkanaKeysInterfaces
  TPPDF:
    url: https://github.com/techprimate/TPPDF.git
    from: 2.4.1
configs:
  Debug: debug
  Snapshot: debug
  AppStore: release
schemes:
  VoiceLog:
    build:
      targets:
        VoiceLog: all
      config: Debug
    test:
      targets:
        - name: VoiceLogTests
    run:
      config: Debug
      commandLineArguments:
        "-com.apple.CoreData.ConcurrencyDebug 1": true
        "-com.apple.CoreData.SQLDebug 1": true
  VoiceLogWatch:
    build:
      targets:
        VoiceLogWatch: all
      config: Debug
    run:
      config: Debug
  SnapshotTests:
    build:
      targets:
        SnapshotTests: test
    test:
      targets:
        - SnapshotTests
      config: Snapshot
targets:
  VoiceLogWatch:
    type: application
    platform: watchOS
    deploymentTarget: "9.0"
    dependencies:
      - package: XLog
      - package: XLang
      - target: VoiceLogWatchWidget
    sources:
      - Watch
      - Shared
    info:
      path: Watch/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        WKCompanionAppBundleIdentifier: app.haibin.voicelog
        NSMicrophoneUsageDescription: "VoiceLog requires access to your microphone."
        UIBackgroundModes: [audio]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.haibin.voicelog.watch
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: true
      configs:
        Debug:
          CODE_SIGN_STYLE: Automatic
        AppStore:
          CODE_SIGN_STYLE: Automatic
  VoiceLogWatchWidget:
    type: app-extension
    platform: watchOS
    deploymentTarget: "9.0"
    sources:
      - WatchWidget
    info:
      path: WatchWidget/Info.plist
      properties:
        CFBundleDisplayName: VoiceLog
        CFBundleShortVersionString: $(MARKETING_VERSION)
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.haibin.voicelog.watch.widget
        GENERATE_INFOPLIST_FILE: true
      configs:
        Debug:
          CODE_SIGN_STYLE: Automatic
        AppStore:
          CODE_SIGN_STYLE: Automatic
  VoiceLogTests:
    type: bundle.unit-test
    platform: iOS
    path: Tests/Info.plist
    sources:
      - Tests
    dependencies:
      - target: VoiceLog
    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1
        PRODUCT_BUNDLE_IDENTIFIER: app.haibin.voicelog.tests
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
        SUPPORTS_MACCATALYST: NO
  VoiceLogWidget:
    type: app-extension
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - WatchWidget
    info:
      path: WatchWidget/Info.plist
      properties:
        CFBundleDisplayName: VoiceLog
        CFBundleShortVersionString: $(MARKETING_VERSION)
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.haibin.voicelog.widget
        GENERATE_INFOPLIST_FILE: true
        SKIP_INSTALL: true
      configs:
        Debug:
          CODE_SIGN_STYLE: Automatic
        AppStore:
          CODE_SIGN_STYLE: Automatic
  VoiceLog:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    dependencies:
      - package: XLog
      - package: XLang
      - package: KeychainAccess
      - package: ArkanaKeys
      - package: ArkanaKeysInterfaces
      - package: ConfettiSwiftUI
      - package: CSV
      - package: TPPDF
      - package: DSWaveformImage
        product: DSWaveformImage
      - package: DSWaveformImage
        product: DSWaveformImageViews
      - target: VoiceLogWatch
      - target: VoiceLogWidget
    sources:
      - Sources
      - Resources
      - Shared
    info:
      path: Resources/Info.plist
      properties:
        NSHumanReadableCopyright: Copyright © 2024 Tarbo Tech, LLC
        CFBundleShortVersionString: $(MARKETING_VERSION)
        AppStoreURL: https://apps.apple.com/us/app/alog/id6451082482
        GIT_HASH: "${GIT_HASH}"
        UILaunchStoryboardName: Launch Screen
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
        ITSAppUsesNonExemptEncryption: false
        NSSpeechRecognitionUsageDescription: "Access to speech recognition functionality is required."
        NSMicrophoneUsageDescription: "VoiceLog requires access to your microphone so that you can record entries in your journal."
        UIBackgroundModes: [audio]
        CFBundleURLTypes:
          - CFBundleTypeRole: Editor
            CFBundleURLName: app.haibin.voicelog
            CFBundleURLSchemes:
              - voicelog
    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1,2
        PRODUCT_BUNDLE_IDENTIFIER: app.haibin.voicelog
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
      configs:
        Debug:
          CODE_SIGN_STYLE: Automatic
        AppStore:
          CODE_SIGN_STYLE: Automatic
        Snapshot:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: [DEBUG, SNAPSHOT]
  SnapshotTests:
    type: bundle.ui-testing
    deploymentTarget: "16.0"
    platform: iOS
    sources: [SnapshotTests]
    dependencies:
      - target: VoiceLog
    settings:
      INFOPLIST_FILE: Resources/Info.plist
