default_platform(:ios)

platform :ios do
  desc "Build"
  lane :beta do

    match({
        type: 'appstore',
    })

    increment_build_number({
      build_number: ENV['BUILD_NUMBER']
    })

    gym ({
      scheme: 'VoiceLog'
    })

    upload_to_testflight(
        apple_id: '6451082482',
        itc_provider: 'ZTQ4TGAKFX',
        skip_submission: true,
        skip_waiting_for_build_processing: true
    )
  end

  lane :tests do
    run_tests(scheme: "VoiceLog", devices: ["iPhone 15 Pro"])
  end
end
